### PR TITLE
fix(plugin_k8s): don't explore folder which don't end with .slice

### LINKED ISSUE #50: K8S plugin goes too deep
**Describe the bug**

When Alumet is launch with k8s plugin, crio's layer are reported, I mean, a pod have crio layers, but we don't want to report it, it's unecessary and too deep. We just want pod's global values

**Environment information**
OS: X
Alumet version: 0.6.0
Enabled plugins: K8s, CSV output (CSV one is not relevant)

: please include the commit hash if it's not a release: This [Alumet](https://github.com/alumet-dev/alumet/releases/tag/v0.6.0)

**To Reproduce**
1. Run alumet local agent or client: **./app-agent**, no arguments are needed
2. Wait alumet for retrieving some values
4. Look in output

**Expected behavior**
The output should not contains lines if their uid is a CRIO part.

**Logs / Output**
Logs are not relevant here,  but here is the csv output example:
image
As we can see, these lines have their columns *uid* containing CRIO layers

### PR DESCRIPTION
**Pull request by AngeCyp**
In the code, when cgroupv2 files are detected, check if it's don't end with ".slice". If not, just look at the next file. 

Fix #50

### CODE REVIEW

File: plugin-cgroupv2/src/k8s/utils.rs [hunk 1]
```diff
@@ -66,6 +66,11 @@ fn list_metric_file_in_dir(
                 .to_str()
                 .with_context(|| format!("Filename is not valid UTF-8: {:?}", path))?;
 
+            // If the dir_uid doesn't end with .slice, we will not find the right files
+            if !(dir_uid.ends_with(".slice")) {
```
Comment (TheElectronWill) [inline plugin-cgroupv2/src/k8s/utils.rs:70]: IMO you can remove the extra parens 
```suggestion
            if !dir_uid.ends_with(".slice") {
```

**Review by TheElectronWill — CHANGES_REQUESTED** [review]

**Comment by TheElectronWill** [comment]
> Too long with no output (exceeded 30s): context deadline exceeded

Hmmm :thinking:

**Comment by TheElectronWill** [comment]
@AngeCyp don't forget to resolve the conversations :)

**Comment by AngeCyp** [comment]
> test failure:
> 
> > Too long with no output (exceeded 30s): context deadline exceeded
> 
> Hmmm 🤔

Do i need to care about this ?

**Comment by TheElectronWill** [comment]
> > test failure:
> > > Too long with no output (exceeded 30s): context deadline exceeded
> > 
> > 
> > Hmmm 🤔
> 
> Do i need to care about this ? @TheElectronWill

No, it's not caused by your change. I'll investigate someday ^^
